name: Flujo para construir y probar el código. Se envía email si su ejecución es exitosa.
on:
  push:  
    branches: [main]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo el código
        run: |
          chmod +x gradlew        
          ./gradlew assemble

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Ejecutando tests
        run: |
          chmod +x gradlew        
          ./gradlew test
  Correo:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Correo
        uses: cinotify/github-action@feaa5fed1588048bd8e14d6b9c26964f9d164a25
        with:
          to: ${{ secrets.EMAIL }}
          subject: "Pipeline de @manmanher realizado con éxito"
          body: "El pipeline fue ejecutado con éxito"
