on:
  workflow_dispatch:
  push:
    branches: [ denortlui ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew assemble
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew test
  Notificacion:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Send mailer
        uses: dawidd6/action-send-mail@v3.7.2
        with:
          connection_url: ${{secrets.URL_SMTP}}
         # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 25
          username: ${{secrets.CORREO_FROM}}
          password: ${{secrets.CONTRA_CORREO}}
          subject: 'Notificacion del proyecto FS'
          to: ${{secrets.CORREO_TO}}
          from: 'Denis'
          body: 'Test superados satisfactoriamente'
      - name: Mensaje de fin
        run: echo 'Correo enviado :)'
